{{- if .Values.route.enabled -}}
{{ $fullName := include "litmus-portal.fullname" . }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-route
  labels:
    app.kubernetes.io/part-of: {{ $fullName }}-server
    app.kubernetes.io/part-of: {{ $fullName }}-frontend
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: litmus.apps.ocp.bdmsky.net
  {{- end }}
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: litmusportal-frontend-service
{{- end }}