{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
  - verbs:
      - create
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - create
      - get
      - list
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - get
      - watch
      - create
      - list
    apiGroups:
      - ""
    resources:
      - configmaps
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - workfloweventbindings
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get","list"]
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - replicationcontrollers
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - patch
  - apiGroups:
      - "policy"
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - get
      - delete
  - apiGroups:
      - eventtracker.litmuschaos.io
    resources:
      - eventtrackerpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventtracker.litmuschaos.io
    resources:
      - eventtrackerpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps.openshift.io"]
    resources: ["deploymentconfigs"]
    verbs: ["get","list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","create","deletecollection"]
  - apiGroups: [""]
    resources: ["pods","pods/exec","configmaps","events","services"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines","chaosexperiments","chaosresults"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
{{ end }}
