{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
  - verbs:
      - create
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - create
      - get
      - list
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ""
    resources:
      - configmaps
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - patch
  - apiGroups:
      - "policy"
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - get
      - delete
{{ end }}
