{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  namespace:  {{ .Release.Namespace }}
rules:
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
  - verbs:
      - create
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - services
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - create
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - configmaps
{{ end }}
